begin;
create extension if not exists pgcrypto;
create extension if not exists citext;
-- =========================================================
-- ENUMS
-- =========================================================
do $$ begin
  create type public.content_status as enum ('draft', 'review', 'scheduled', 'published', 'archived');
exception
  when duplicate_object then null;
end $$;
do $$ begin
  create type public.asset_status as enum ('pending', 'processing', 'ready', 'failed');
exception
  when duplicate_object then null;
end $$;
do $$ begin
  create type public.asset_visibility as enum ('private', 'internal', 'public');
exception
  when duplicate_object then null;
end $$;
do $$ begin
  create type public.solution_stage as enum ('concept', 'private_beta', 'early_access', 'public');
exception
  when duplicate_object then null;
end $$;
do $$ begin
  create type public.contact_status as enum ('new', 'contacted', 'qualified', 'converted', 'closed');
exception
  when duplicate_object then null;
end $$;
do $$ begin
  create type public.faq_scope as enum ('general', 'media', 'solutions', 'platform');
exception
  when duplicate_object then null;
end $$;
-- =========================================================
-- HELPERS
-- =========================================================
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (
    id,
    email,
    display_name,
    avatar_url
  )
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1)),
    new.raw_user_meta_data ->> 'avatar_url'
  )
  on conflict (id) do update
  set
    email = excluded.email,
    display_name = coalesce(excluded.display_name, public.profiles.display_name),
    avatar_url = coalesce(excluded.avatar_url, public.profiles.avatar_url),
    updated_at = now();
  return new;
end;
$$;
-- =========================================================
-- USERS / ROLES
-- =========================================================
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email citext unique,
  display_name text,
  avatar_url text,
  bio text,
  youtube_channel_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug in ('admin', 'editor', 'viewer')),
  label text not null,
  created_at timestamptz not null default now()
);
insert into public.roles (slug, label)
values
  ('admin', 'Administrator'),
  ('editor', 'Editor'),
  ('viewer', 'Viewer')
on conflict (slug) do nothing;
create table if not exists public.user_roles (
  user_id uuid not null references public.profiles(id) on delete cascade,
  role_id bigint not null references public.roles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, role_id)
);
-- =========================================================
-- SETTINGS / MEDIA
-- =========================================================
create table if not exists public.site_settings (
  id bigint generated by default as identity primary key,
  key text not null unique,
  value_json jsonb not null default '{}'::jsonb,
  description text,
  is_public boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.media_assets (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid references public.profiles(id) on delete set null,
  bucket_name text not null,
  object_path text not null,
  file_name text not null,
  mime_type text,
  size_bytes bigint check (size_bytes is null or size_bytes >= 0),
  width integer check (width is null or width >= 0),
  height integer check (height is null or height >= 0),
  duration_seconds integer check (duration_seconds is null or duration_seconds >= 0),
  alt_text text,
  caption text,
  status public.asset_status not null default 'pending',
  visibility public.asset_visibility not null default 'private',
  checksum text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (bucket_name, object_path)
);
create table if not exists public.media_derivatives (
  id uuid primary key default gen_random_uuid(),
  parent_asset_id uuid not null references public.media_assets(id) on delete cascade,
  kind text not null,
  bucket_name text not null,
  object_path text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (parent_asset_id, kind, object_path)
);
create table if not exists public.upload_jobs (
  id uuid primary key default gen_random_uuid(),
  asset_id uuid references public.media_assets(id) on delete cascade,
  requested_by uuid references public.profiles(id) on delete set null,
  job_type text not null,
  status public.asset_status not null default 'pending',
  attempt_count integer not null default 0,
  error_message text,
  payload jsonb not null default '{}'::jsonb,
  run_after timestamptz not null default now(),
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
-- =========================================================
-- EDITORIAL
-- =========================================================
create table if not exists public.authors (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid unique references public.profiles(id) on delete set null,
  name text not null,
  slug text not null unique,
  title text,
  bio text,
  avatar_url text,
  is_featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  slug text not null unique,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.tags (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  slug text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.articles (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text not null unique,
  excerpt text,
  body jsonb not null default '[]'::jsonb,
  status public.content_status not null default 'draft',
  category_id uuid references public.categories(id) on delete set null,
  author_id uuid references public.authors(id) on delete set null,
  cover_asset_id uuid references public.media_assets(id) on delete set null,
  seo_title text,
  seo_description text,
  read_time_minutes integer check (read_time_minutes is null or read_time_minutes >= 0),
  is_featured boolean not null default false,
  scheduled_at timestamptz,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.article_blocks (
  id uuid primary key default gen_random_uuid(),
  article_id uuid not null references public.articles(id) on delete cascade,
  block_type text not null,
  position integer not null check (position >= 0),
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (article_id, position)
);
create table if not exists public.article_tags (
  article_id uuid not null references public.articles(id) on delete cascade,
  tag_id uuid not null references public.tags(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (article_id, tag_id)
);
-- =========================================================
-- VIDEOS
-- =========================================================
create table if not exists public.videos (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text not null unique,
  excerpt text,
  youtube_video_id text unique,
  external_url text,
  thumbnail_asset_id uuid references public.media_assets(id) on delete set null,
  duration_seconds integer check (duration_seconds is null or duration_seconds >= 0),
  status public.content_status not null default 'draft',
  is_featured boolean not null default false,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.video_playlists (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text not null unique,
  description text,
  is_featured boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.video_playlist_items (
  playlist_id uuid not null references public.video_playlists(id) on delete cascade,
  video_id uuid not null references public.videos(id) on delete cascade,
  position integer not null check (position >= 0),
  created_at timestamptz not null default now(),
  primary key (playlist_id, video_id),
  unique (playlist_id, position)
);
-- =========================================================
-- SOLUTIONS / GROWTH
-- =========================================================
create table if not exists public.solutions (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  tagline text,
  description text,
  stage public.solution_stage not null default 'concept',
  status public.content_status not null default 'draft',
  hero_asset_id uuid references public.media_assets(id) on delete set null,
  demo_url text,
  docs_url text,
  website_url text,
  waitlist_count integer not null default 0,
  featured boolean not null default false,
  sort_order integer not null default 0,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.solution_features (
  id uuid primary key default gen_random_uuid(),
  solution_id uuid not null references public.solutions(id) on delete cascade,
  title text not null,
  description text,
  icon text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.solution_testimonials (
  id uuid primary key default gen_random_uuid(),
  solution_id uuid references public.solutions(id) on delete cascade,
  name text not null,
  role text,
  company text,
  quote text not null,
  rating integer check (rating is null or (rating between 1 and 5)),
  is_beta_feedback boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.faqs (
  id uuid primary key default gen_random_uuid(),
  question text not null,
  answer text not null,
  scope public.faq_scope not null default 'general',
  solution_id uuid references public.solutions(id) on delete cascade,
  status public.content_status not null default 'draft',
  sort_order integer not null default 0,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.waitlist_entries (
  id uuid primary key default gen_random_uuid(),
  email citext not null,
  full_name text,
  organization text,
  notes text,
  solution_id uuid references public.solutions(id) on delete set null,
  source text,
  submitted_from text,
  status public.contact_status not null default 'new',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (email, solution_id)
);
create table if not exists public.demo_requests (
  id uuid primary key default gen_random_uuid(),
  email citext not null,
  full_name text not null,
  organization text,
  role_title text,
  team_size text,
  message text,
  solution_id uuid references public.solutions(id) on delete set null,
  status public.contact_status not null default 'new',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
-- =========================================================
-- OPS / AUDIT
-- =========================================================
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references public.profiles(id) on delete set null,
  action text not null,
  target_table text,
  target_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
-- =========================================================
-- INDEXES
-- =========================================================
create index if not exists idx_user_roles_user_id on public.user_roles (user_id);
create index if not exists idx_media_assets_owner on public.media_assets (owner_user_id);
create index if not exists idx_media_assets_status_visibility on public.media_assets (status, visibility);
create index if not exists idx_upload_jobs_status_run_after on public.upload_jobs (status, run_after);
create index if not exists idx_articles_status_published_at on public.articles (status, published_at desc);
create index if not exists idx_articles_category_id on public.articles (category_id);
create index if not exists idx_article_blocks_article_id on public.article_blocks (article_id);
create index if not exists idx_videos_status_published_at on public.videos (status, published_at desc);
create index if not exists idx_video_playlist_items_video_id on public.video_playlist_items (video_id);
create index if not exists idx_solutions_status_published_at on public.solutions (status, published_at desc);
create index if not exists idx_solution_features_solution_sort on public.solution_features (solution_id, sort_order);
create index if not exists idx_solution_testimonials_solution_id on public.solution_testimonials (solution_id);
create index if not exists idx_faqs_scope_status on public.faqs (scope, status);
create index if not exists idx_waitlist_entries_solution_created on public.waitlist_entries (solution_id, created_at desc);
create index if not exists idx_demo_requests_solution_created on public.demo_requests (solution_id, created_at desc);
create index if not exists idx_audit_logs_actor_created on public.audit_logs (actor_user_id, created_at desc);
-- =========================================================
-- UPDATED_AT TRIGGERS
-- =========================================================
drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();
drop trigger if exists set_site_settings_updated_at on public.site_settings;
create trigger set_site_settings_updated_at
before update on public.site_settings
for each row execute function public.set_updated_at();
drop trigger if exists set_media_assets_updated_at on public.media_assets;
create trigger set_media_assets_updated_at
before update on public.media_assets
for each row execute function public.set_updated_at();
drop trigger if exists set_upload_jobs_updated_at on public.upload_jobs;
create trigger set_upload_jobs_updated_at
before update on public.upload_jobs
for each row execute function public.set_updated_at();
drop trigger if exists set_authors_updated_at on public.authors;
create trigger set_authors_updated_at
before update on public.authors
for each row execute function public.set_updated_at();
drop trigger if exists set_categories_updated_at on public.categories;
create trigger set_categories_updated_at
before update on public.categories
for each row execute function public.set_updated_at();
drop trigger if exists set_tags_updated_at on public.tags;
create trigger set_tags_updated_at
before update on public.tags
for each row execute function public.set_updated_at();
drop trigger if exists set_articles_updated_at on public.articles;
create trigger set_articles_updated_at
before update on public.articles
for each row execute function public.set_updated_at();
drop trigger if exists set_videos_updated_at on public.videos;
create trigger set_videos_updated_at
before update on public.videos
for each row execute function public.set_updated_at();
drop trigger if exists set_video_playlists_updated_at on public.video_playlists;
create trigger set_video_playlists_updated_at
before update on public.video_playlists
for each row execute function public.set_updated_at();
drop trigger if exists set_solutions_updated_at on public.solutions;
create trigger set_solutions_updated_at
before update on public.solutions
for each row execute function public.set_updated_at();
drop trigger if exists set_solution_features_updated_at on public.solution_features;
create trigger set_solution_features_updated_at
before update on public.solution_features
for each row execute function public.set_updated_at();
drop trigger if exists set_solution_testimonials_updated_at on public.solution_testimonials;
create trigger set_solution_testimonials_updated_at
before update on public.solution_testimonials
for each row execute function public.set_updated_at();
drop trigger if exists set_faqs_updated_at on public.faqs;
create trigger set_faqs_updated_at
before update on public.faqs
for each row execute function public.set_updated_at();
drop trigger if exists set_waitlist_entries_updated_at on public.waitlist_entries;
create trigger set_waitlist_entries_updated_at
before update on public.waitlist_entries
for each row execute function public.set_updated_at();
drop trigger if exists set_demo_requests_updated_at on public.demo_requests;
create trigger set_demo_requests_updated_at
before update on public.demo_requests
for each row execute function public.set_updated_at();
-- =========================================================
-- AUTH TRIGGER
-- =========================================================
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();
commit;
